services:
  influxdb:
    restart: unless-stopped
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - "${HOME}/local/docker-volumes/docker-speedtest-grafana/influxdb:/var/lib/influxdb"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"
      - "INFLUXDB_DB=speedtest"
  grafana:
    restart: unless-stopped
    image: grafana/grafana:6.7.2
    volumes:
      - "${HOME}/local/docker-volumes/docker-speedtest-grafana/provisioning:/etc/grafana/provisioning"
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - "GF_SERVER_ROOT_URL=https://vhost.lab.moseleynet.net/speedtest/"
      - "GF_SERVER_DOMAIN=http://vhost.lab.moseleynet.net"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    depends_on:
      - influxdb

  speedtest:
    restart: unless-stopped
    image: frdmn/speedtest-grafana:latest
    container_name: speedtest
    environment:
      - "SPEEDTEST_INTERVAL=${SPEEDTEST_SPEEDTEST_INTERVAL}"
      - "SPEEDTEST_HOST=${SPEEDTEST_HOST}"
    depends_on:
      - influxdb

networks:
  default:
    external: true
    name: lsio
